name: heroescompanion
description: "Компаньон для настольной игры «Герои»."
publish_to: 'none'
version: 3.0.0+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.6.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/factions/
    - assets/units/
    - assets/faction_background/
    - assets/score_screen/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon_h.PNG"
  adaptive_icon_background: "assets/icon/icon_h.PNG"
  adaptive_icon_foreground: "assets/icon/icon_h.PNG"
  adaptive_icon_foreground_inset: 0
